
set(ANDROID TRUE)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "armv7-a")
set(CMAKE_SYSTEM_VERSIIN 1)

set(ANDROID_PLATFORM "15")
set(CROSS_PREFIX "arm-linux-androideabi-")

set(CMAKE_PLATFORM_NO_VERSIONED_SONAME 1)


set(CMAKE_C_COMPILER ${TOOLCHAIN_ROOT}/bin/${CROSS_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/bin/${CROSS_PREFIX}g++)

#__USE_GNU - work around for crystax: see revision #9041d6a at crystax/android-platform-bionic
set(ANDROID_CFLAGS "-march=${CMAKE_SYSTEM_PROCESSOR} -mfloat-abi=softfp -mfpu=neon -D__USE_GNU=1")
set(ANDROID_LDFLAGS "")

#set(CMAKE_C_FLAGS "-std=gnu++14 ${ANDROID_CFLAGS}" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "-std=gnu++14 ${ANDROID_CFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${ANDROID_CFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${ANDROID_CFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${ANDROID_LDFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${ANDROID_LDFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${ANDROID_LDFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} ${ANDROID_LDFLAGS}" CACHE STRING "" FORCE)

if (NOT DEFINED CMAKE_FIND_ROOT_PATH)
	if (DEFINED CMAKE_SYSROOT)
		set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT} CACHE STRING "" FORCE)
	endif()
endif()

if (DEFINED CMAKE_FIND_ROOT_PATH)
	set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
	set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
	set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
	set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

